### PR TITLE
Artemis build without FORCEINT32 now correctly uses BigInteger in SystemBitManager

### LINKED ISSUE #93: More than 64 processors
I have more than 64 processors in my game and I discovered a bug where the flags aren't set up correctly for the bit system manager.

Super easy fix though. In SystemBitManager.cs you need a replacement of

```
bit = 1L << this.position;
```
with 
```
bit = BigInteger.One << this.position;
```

in the else statement. I guess no one has built a game with so many processors yet?

1L (1 64int) was looping over after it was shifted 64 bits. With the fix, we are using the as-large-as-needed integer to set the correct flag.

My branch requires me to add something to IComponent, so I can't make a pull request. Can someone else make this change?

### PR DESCRIPTION
**Pull request by Maximusya**
Fixes #93

### CODE REVIEW

**Comment by Maximusya** [comment]
Please review and merge if it's ok

**Comment by KellanHiggins** [comment]
I am sure these are equal, but I specifically used the static method BigInteger.One to give the system a 1. Probably works the same though.

**Comment by Maximusya** [comment]
I placed `new BigInteger(1)` because in Unity5 pull request @iskar909 used it like this instead of `BigInteger.One`: I assumed there was no such definition in Unity5-referenced library with BigInteger.
@iskar909, correct me if I am wrong

**Comment by iskar909** [comment]
Sounds correct

**Pull request merged**
