### PR TITLE
Adds visual debugging functionality identical to Entitas 

### PR DESCRIPTION
**Pull request by ghost**
Early version of ArtemisUnity visual debugging.

does not modify or tamper with original artemis code (nor is any code added to foundation; this is a unity editor layer for Artemis Unity), uses systems to manage visual debugging.

At the moment you can display entities and their components, delete an entity from inspector and remove components from inspector as well as edit component properties (supports fields but not yet included in search)

### CODE REVIEW

**Comment by T2RKUS** [comment]
Features example:
screen shot 2016-05-06 at 17 05 00
screen shot 2016-05-06 at 17 05 04
screen shot 2016-05-06 at 17 05 13

**Comment by thelinuxlich** [comment]
Wow, this is very cool! Can you share your experience replacing the standard Unity component system with Artemis?

**Comment by T2RKUS** [comment]
I came across Entitas by Wooga a while back when i wanted to organise my code better and make it more modular but i didn't like the code generation feature. Artemis is awesome but didn't have any visual debugging features like Entitas did; so I thought i'd bridge the gap. some of the design such as the type drawer was inspired by Entitas. https://github.com/sschmid/Entitas-CSharp

One of the things i didn't want to do was modify or have to change any of the original artemis code but just provide an editor layer using Systems (which are automatically added to layer 0 through attributes) and the framework itself. i really value code reuse.

**Comment by T2RKUS** [comment]
I currently the following features i plan to implement into Artemis Visual Debugging for unity

- be able to delete multiple entities
- be able to bulk add components to selected entities and bulk delete them
- be able to add components to entities from component pool
- be able to add components to entities and search for components in entities 
- be able to add entities from entity templates
- being able to add multiple entities using a window with search feature (checkbox for multi select)
- being able to add multiple systems using a window with search feature (checkbox for multi select)

**Comment by KellanHiggins** [comment]
Looks awesome! Thanks for contributing.

**Comment by T2RKUS** [comment]
Updates:
screen shot 2016-05-07 at 18 26 15
screen shot 2016-05-07 at 18 26 25
screen shot 2016-05-07 at 18 26 30

**Comment by T2RKUS** [comment]
Latest feature (adding components & more type drawers)
screen shot 2016-05-09 at 18 53 08
screen shot 2016-05-09 at 18 53 11
screen shot 2016-05-09 at 18 53 17

**Comment by T2RKUS** [comment]
Added 'x' reset to default value button In case you just want to reset a specific property/field to its default value (reinitialize value - uses default())
screen shot 2016-05-09 at 19 44 47

**Comment by T2RKUS** [comment]
Add multiple components to more than one entity at once
screen shot 2016-05-09 at 21 25 50

**Comment by T2RKUS** [comment]
Are there any features that anyone wants besides those mentioned above? While i plan to always support this layer i'm making, after this i will be making a new and much faster ECS System using concepts from both Entitas and Artemis.

**Pull request closed without merging**
